BulkyBookWeb/BulkyBookWeb/Controllers/CategoryController.cs
using BulkyBookWeb.Data;
using BulkyBookWeb.Models;
using Microsoft.AspNetCore.Mvc;

namespace BulkyBookWeb.Controllers
{
    public class CategoryController : Controller
    {
        private readonly ApplicationDbContext _db;
        public CategoryController(ApplicationDbContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            IEnumerable<Category> objCategoryList = _db.Categories;
            return View(objCategoryList);
        }

        //GET
        public IActionResult Create()
        {
            return View();
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Category obj)
        {
            if (ModelState.IsValid)
            {
                _db.Categories.Add(obj);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(obj);

        }

        //GET
        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var categoryFromDb = _db.Categories.Find(id);

            if (categoryFromDb == null)
            {
                return NotFound();
            }
            return View(categoryFromDb);
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Category obj)
        {
            if (ModelState.IsValid)
            {
                _db.Categories.Update(obj);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(obj);

        }

        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var categoryFromDb = _db.Categories.Find(id);

            if (categoryFromDb == null)
            {
                return NotFound();
            }
            return View(categoryFromDb);
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(Category obj)
        {
            if (ModelState.IsValid)
            {
                _db.Categories.Remove(obj);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(obj);

        }
    }
}

BulkyBookWeb/BulkyBookWeb/Controllers/LogInController.cs
using BulkyBookWeb.Data;
using BulkyBookWeb.Models;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace BulkyBookWeb.Controllers
{
    public class LogInController : Controller
    {

        private readonly ApplicationDbContext _db;
        private readonly HttpClient _httpClient;
        public LogInController(ApplicationDbContext db, HttpClient httpClient)
        {
            _db = db;
            _httpClient = httpClient;

        }


        public IActionResult Index()
        {
            return View();
        }

        //Post
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Index(User obj)
        {
            if (ModelState.IsValid)
            {

                var user = _db.Users.FirstOrDefault(u => u.Username == obj.Username && u.Password == obj.Password && u.Email == obj.Email);
                Console.WriteLine(user);
                if (user !=null)
                {

                    TempData["success"] = "Succesfully Logged In. Hello " + obj.Username + "!";
                    return RedirectToAction("CoinPrice");
                }
                else
                {
                    TempData["error"] = "Credentials not recognized";
                    return View(obj);
                }
                
            }
            return View(obj);
     
        }

        public async Task<IActionResult> CoinPrice()
        {
            HttpResponseMessage response = await _httpClient.GetAsync("https://api.coingecko.com/api/v3/simple/price?ids=bitcoin%2Clitecoin%2Cdogecoin%2Cethereum%2Ctether%2Ctatecoin&vs_currencies=eur");
            if (response.IsSuccessStatusCode)
            {
                // Lesen Sie den Inhalt der Antwort als JSON
                string jsonString = await response.Content.ReadAsStringAsync();
                TempData["lastUpdate"] = response.Headers.Age;

                // Deserialisieren Sie das JSON in ein Objekt
                var data = JsonConvert.DeserializeObject<Dictionary<string, Dictionary<string, decimal>>>(jsonString);

                List<CoinPriceList> coinPriceList = new List<CoinPriceList>();

                // Iterieren Sie über die Schlüssel-Wert-Paare im data-Objekt
                foreach (var coinEntry in data)
                {
                    string coinName = coinEntry.Key;
                    decimal eurPrice = coinEntry.Value["eur"];

                    // Erstellen Sie ein neues CoinPriceList-Objekt und fügen Sie es zur Liste hinzu
                    CoinPriceList coin = new CoinPriceList
                    {
                        CoinName = coinName,
                        EurPrice = eurPrice
                    };

                    coinPriceList.Add(coin);
                }

                return View(coinPriceList);
            }

            return View();
        }

    }
}

BulkyBookWeb/BulkyBookWeb/Controllers/WeatherController.cs
using BulkyBookWeb.Data;
using BulkyBookWeb.Models;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using NuGet.Protocol;
using System.Runtime.Remoting;

namespace BulkyBookWeb.Controllers
{

    public class WeatherController : Controller
    {
        private readonly HttpClient _httpClient;
        public WeatherController(HttpClient httpClient)
        {
            _httpClient = httpClient;

        }
        public IActionResult Index()
        {
            return View();
        }


        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public async Task<IActionResult> Index(RegionWeatherData obj)
        {

            //ANDERE GEOCODING API VERWENDEN!
            //GEOCODING API
            string coordsAPI = "https://api.opencagedata.com/geocode/v1/json?q=" + obj.Region.RegionName + "&key=6a8a5216bd424dd1a30b351e78199544";
            HttpResponseMessage responseFromCoordsAPI = await _httpClient.GetAsync(coordsAPI);
            if (responseFromCoordsAPI.IsSuccessStatusCode)
            {
                string jsonString = await responseFromCoordsAPI.Content.ReadAsStringAsync();
                JToken token = JToken.Parse(jsonString);

                JObject newObj = new JObject();
                newObj["lat"] = token["results"][0]["geometry"]["lat"];
                newObj["lon"] = token["results"][0]["geometry"]["lng"];

                //API FÜR WETTER

                string weatherAPI = "https://api.openweathermap.org/data/2.5/weather?lat=" + newObj["lat"] + "&lon=" + newObj["lon"] + "&appid=0bd3c9b3aa88d0263f746e687d27b64e";
                HttpResponseMessage responseFromWeatherAPI = await _httpClient.GetAsync(weatherAPI);
                if (responseFromWeatherAPI.IsSuccessStatusCode)
                {
                    jsonString = await responseFromWeatherAPI.Content.ReadAsStringAsync();
                    var weatherData = JsonConvert.DeserializeObject<WeatherData>(jsonString);
                    var data = new RegionWeatherData();
                    data.Weather = weatherData;
                    TempData["ReadyForWeather"] = "yes";
                    TempData["js"] = "yes";
                    return View(data);
                }
                TempData["LocationFound"] = "no";
                return View();
            }
            TempData["LocationFound"] = "no";
            return View();
            
        }
    }
}

BulkyBookWeb/BulkyBookWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BulkyBookWeb</title>
    <link rel="stylesheet" href="~/css/bootswatchTheme.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BulkyBookWeb.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BulkyBookWeb</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="Index">Category</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="LogIn" asp-action="Index">LogIn</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="LogIn" asp-action="CoinPrice">Crypto</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Weather" asp-action="Index">Weather</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - BulkyBookWeb - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>